In [1]:
pip install transformers

Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np
import pandas as pd

In [123]:
from transformers import pipeline
classifier_robertuito = pipeline("sentiment-analysis", model="pysentimiento/robertuito-sentiment-analysis")

# Base completa

In [18]:
base_consolidada = pd.read_excel("Informe Consolidado Bases 2023 de Experiencia.xlsx", sheet_name= "Base Consolidada")
base_consolidada.head()

Fecha              Producto  ID Cliente  \
0  14 de febrero   Crédito Hipotecario  1005813290   
1   6 de febrero   Crédito Hipotecario    70978636   
2  24 de febrero  Leasing Habitacional    10528109   
3  27 de febrero   Crédito Hipotecario    30300975   
4  22 de febrero   Crédito Hipotecario  1037588239   

                    Nombre Cliente  \
0      ANDREA MARCELA MENDEZ ORTIZ   
1      JOSE MANUEL RODRIGUEZ BERNA   
2  ALVARO FERNANDO SANSON GUERRERO   
3      MARIA NANCY FRANCO CARDENAS   
4      JUAN FELIPE MONTOYA LONDOÑO   

  Tipo de cambio ( solicitud / mantenimiento )        SEGMENTO  P1  P2  P3  \
0                         Disminución de plazo        PERSONAL   5   5   5   
1                        Cambio de pesos a UVR        PERSONAL   1   1   1   
2             A1- Abono con modificación plazo    PREFERENCIAL   5   5   5   
3                         Disminución de plazo  INDEPENDIENTES   4   4   4   
4                        Cambio de pesos a UVR        PERSONAL   3   5   2   

   P4  P5                                           Verbatim  \
0   5   5               La atención y gestión de la asesora.   
1   1   1  Me siento engañado por el banco porque en el m...   
2   5   5  Todo muy agil y preciso. La amabilidad de los ...   
3   4   3  al principio la asesora me dijo que no era viable   
4   5   5  LOS INTERESES DEL CREDITO SON CRIMINALES, YA E...   

                CLASIFICACIÓN VERBATIM AREA SOLICITANTE  \
0           Amabilidad y buen servicio              PIC   
1  Falta de claridad en la información              PIC   
2           Amabilidad y buen servicio              CAC   
3  Falta de claridad en la información              PIC   
4  Falta de claridad en la información              PIC   

  ENCUESTA ( MES PROCESO )             GESTION  \
0                  Febrero                  ok   
1                  Febrero                 NaN   
2                  Febrero                  ok   
3                  Febrero  Comercial Asesoria   
4                  Febrero                 NaN   

                  GESTIÓN A REALIZAR POR LA SECCIÓN2  \
0                                                 ok   
1  POSTVENTA: Revisar condiciones en instrumentac...   
2                                                 ok   
3                               COMERCIAL - Asesoría   
4  POSTVENTA: Revisar como lo podemos remitir a f...   

                    Respuesta a validacion encuentas  \
0                                                NaN   
1  1. cliente solicita credito en pesos pero vali...   
2                                                NaN   
3                                                NaN   
4  1. Credito 90000150515 desembolsado en UVR y m...   

                                   INVESTIGACIÓN E2E  \
0                                                NaN   
1  1. ha radicado varios reclamos 8013257881 , 80...   
2                                                NaN   
3                                                NaN   
4  1. radico reclamo en sap 8013125977  donde ind...   

                                            Acciones  
0                                                NaN  
1  Asesoria comercial\nrevisar definiciones condi...  
2                                                NaN  
3                                                NaN  
4                                                NaN

In [88]:
base_consolidada.shape

(321, 20)

In [144]:
verbatims = base_consolidada["Verbatim"].to_numpy().tolist()
verbatims[2]

'Todo muy agil y preciso. La amabilidad de los asesores excelente'

In [166]:
classifier_robertuito(verbatims[:30])

[{'label': 'NEU', 'score': 0.4909251630306244},
 {'label': 'NEG', 'score': 0.9759020209312439},
 {'label': 'POS', 'score': 0.9679266810417175},
 {'label': 'NEG', 'score': 0.5400736331939697},
 {'label': 'NEG', 'score': 0.9312734007835388},
 {'label': 'POS', 'score': 0.962191641330719},
 {'label': 'POS', 'score': 0.8964368104934692},
 {'label': 'NEG', 'score': 0.9572692513465881},
 {'label': 'NEU', 'score': 0.8196012377738953},
 {'label': 'NEG', 'score': 0.8562747836112976},
 {'label': 'POS', 'score': 0.8444222211837769},
 {'label': 'NEU', 'score': 0.7308128476142883},
 {'label': 'NEU', 'score': 0.5154762268066406},
 {'label': 'NEG', 'score': 0.8003345131874084},
 {'label': 'POS', 'score': 0.8863541483879089},
 {'label': 'POS', 'score': 0.8694957494735718},
 {'label': 'NEU', 'score': 0.8686655759811401},
 {'label': 'POS', 'score': 0.9217601418495178},
 {'label': 'NEG', 'score': 0.9606348276138306},
 {'label': 'NEU', 'score': 0.5740540027618408},
 {'label': 'POS', 'score': 0.655703961849

## Preprocessing with a tokenizer

In [129]:
from transformers import AutoTokenizer

checkpoint = "pysentimiento/robertuito-sentiment-analysis"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [158]:
inputs = tokenizer(verbatims[:120], padding=True, truncation=True, return_tensors="tf")
print(inputs)

{'input_ids': <tf.Tensor: shape=(120, 128), dtype=int32, numpy=
array([[    0,   446,  2831, ...,     1,     1,     1],
       [    0,   474,  1617, ...,     1,     1,     1],
       [    0,   658,   828, ...,     1,     1,     1],
       ...,
       [    0,  9581,  1448, ...,     1,     1,     1],
       [    0, 16224,     2, ...,     1,     1,     1],
       [    0,   471,  4596, ...,     1,     1,     1]])>, 'token_type_ids': <tf.Tensor: shape=(120, 128), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(120, 128), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])>}


## Going through the model

In [159]:
from transformers import TFAutoModel

checkpoint = "pysentimiento/robertuito-sentiment-analysis"
model = TFAutoModel.from_pretrained(checkpoint)

Some layers from the model checkpoint at pysentimiento/robertuito-sentiment-analysis were not used when initializing TFRobertaModel: ['classifier']
- This IS expected if you are initializing TFRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFRobertaModel were not initialized from the model checkpoint at pysentimiento/robertuito-sentiment-analysis and are newly initialized: ['roberta/pooler/dense/bias:0', 'roberta/pooler/dense/kernel:0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [160]:
outputs = model(inputs)
print(outputs.last_hidden_state.shape)

(120, 128, 768)


In [161]:
from transformers import TFAutoModelForSequenceClassification

checkpoint = "pysentimiento/robertuito-sentiment-analysis"
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(inputs)

All model checkpoint layers were used when initializing TFRobertaForSequenceClassification.

All the layers of TFRobertaForSequenceClassification were initialized from the model checkpoint at pysentimiento/robertuito-sentiment-analysis.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForSequenceClassification for predictions without further training.


In [162]:
print(outputs.logits.shape)

(120, 3)


## Postprocessing the output

In [163]:
print(outputs.logits)

tf.Tensor(
[[-2.6344576   2.236011    0.5960978 ]
 [ 4.4543657  -1.0625751  -3.7273278 ]
 [-2.8050804  -0.6621889   4.650268  ]
 [ 1.953229    1.7546555  -3.7626657 ]
 [ 3.058857   -0.05248839 -3.7850227 ]
 [-2.520139   -0.751033    4.347985  ]
 [-2.4052744  -0.35585994  3.9118686 ]
 [ 4.5311584  -2.004209   -2.9158907 ]
 [-0.13447618  2.9695332  -2.333219  ]
 [ 1.8279145   2.0232086  -3.715876  ]
 [-3.6559558   1.6824533   2.409151  ]
 [-1.4135528   3.5033185  -2.1312985 ]
 [-0.54361403  0.983561   -0.53918886]
 [ 3.7216444  -0.27059633 -3.607942  ]
 [-2.522455   -0.8716655   4.4637003 ]
 [-3.7129445   2.5458012   1.6032294 ]
 [-1.32399     3.0913951  -2.1415496 ]
 [-3.576511    1.445176    2.9198797 ]
 [ 4.1756277  -0.8148148  -3.7639637 ]
 [-0.47799084  1.3016397  -0.78509307]
 [-2.9667509   0.18080163  3.28468   ]
 [-1.3483262   2.0628788  -0.9476793 ]
 [-3.0348687   0.01618944  3.9077945 ]
 [ 4.659825   -1.7732699  -3.2727466 ]
 [-0.5580863   1.1693796  -0.6735177 ]
 [ 2.667263   

In [139]:
verbatims[:3]

['La atención y gestión de la asesora.',
 'Me siento engañado por el banco porque en el momento de aprobación del crédito era en pesos y luego ni nos informaron cuando el desembolso y lo hicieron en uvr. El cual nos a traído muchos problemas. Luego hicimos el cambio de uvr a pesos y nos damos cuenta que el capital sigue subiendo.',
 'Todo muy agil y preciso. La amabilidad de los asesores excelente']

In [164]:
import tensorflow as tf

predictions = tf.math.softmax(outputs.logits, axis=-1)
print(predictions)

tf.Tensor(
[[6.38261018e-03 8.32177520e-01 1.61439836e-01]
 [9.95720565e-01 4.00092499e-03 2.78530613e-04]
 [5.75171900e-04 4.90279356e-03 9.94521976e-01]
 [5.48488379e-01 4.49705392e-01 1.80628337e-03]
 [9.56382275e-01 4.25982177e-02 1.01946504e-03]
 [1.03304791e-03 6.05945522e-03 9.92907524e-01]
 [1.77698385e-03 1.37953572e-02 9.84427631e-01]
 [9.97969687e-01 1.44824933e-03 5.81975910e-04]
 [4.27385680e-02 9.52519953e-01 4.74152388e-03]
 [4.50535655e-01 5.47702014e-01 1.76234741e-03]
 [1.56311074e-03 3.25410336e-01 6.73026502e-01]
 [7.24309916e-03 9.89223480e-01 3.53355147e-03]
 [1.51295453e-01 6.96738064e-01 1.51966423e-01]
 [9.81244266e-01 1.81121100e-02 6.43543899e-04]
 [9.19314858e-04 4.79063578e-03 9.94289994e-01]
 [1.37520104e-03 7.18629241e-01 2.79995590e-01]
 [1.18828062e-02 9.82870817e-01 5.24635334e-03]
 [1.22637406e-03 1.86000347e-01 8.12773287e-01]
 [9.92891908e-01 6.75430149e-03 3.53819079e-04]
 [1.30493104e-01 7.73519456e-01 9.59874988e-02]
 [1.84150750e-03 4.28684764e-

In [138]:
model.config.id2label

{0: 'NEG', 1: 'NEU', 2: 'POS'}

## Models

In [146]:
from transformers import BertConfig, TFBertModel

# Building the config
config = BertConfig()

# Building the model from the config
model = TFBertModel(config)

In [148]:
from transformers import TFBertModel

model = TFAutoModel.from_pretrained("pysentimiento/robertuito-sentiment-analysis")

Some layers from the model checkpoint at pysentimiento/robertuito-sentiment-analysis were not used when initializing TFRobertaModel: ['classifier']
- This IS expected if you are initializing TFRobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFRobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFRobertaModel were not initialized from the model checkpoint at pysentimiento/robertuito-sentiment-analysis and are newly initialized: ['roberta/pooler/dense/bias:0', 'roberta/pooler/dense/kernel:0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


# Base No clasificados

In [167]:
base_NC = pd.read_excel("Verbatims No Clasificados.xlsx")
base_NC.head()

Fecha              Producto  ID Cliente  \
0   2 de febrero   Crédito Hipotecario    52852931   
1   9 de febrero   Crédito Hipotecario     8784159   
2   6 de febrero  Leasing Habitacional    43566444   
3  27 de febrero  Leasing Habitacional    78691382   
4  14 de febrero  Leasing Habitacional  1143824623   

                  Nombre Cliente  \
0    ANA CECILIA BURGOS GONZALEZ   
1        GILBERTO URIBE BARLETTA   
2   DIANA CECILIA RENDON RAMIREZ   
3  EUGENIO ENRIQUE SALAS MARQUEZ   
4           DANIELA RIVERA MEJIA   

        Tipo de cambio ( solicitud / mantenimiento )      SEGMENTO  P1  P2  \
0                               Disminución de plazo  PREFERENCIAL   2   3   
1                               Disminución de plazo          PLUS   5   5   
2  A4- Aplicación, Reversión o reclasificación No...  PREFERENCIAL   5   5   
3                   D2- Copia o solicitud documentos  PREFERENCIAL   1   1   
4                           A8- Identificación Pagos          PLUS   1   1   

   P3  P4  ...    GESTION                 GESTIÓN A REALIZAR POR LA SECCIÓN2  \
0   2   3  ...        NaN  POSTVENTA: Buscar solicitudes abiertas o cance...   
1   5   5  ...         ok                                                 ok   
2   5   5  ...         ok                                                 ok   
3   1   1  ...  Postventa  POSTVENTA: Escuchar la llamada y que necesita ...   
4   1   1  ...  Postventa  POSTVENTA: Revisar la solicitud del cliente, q...   

                    Respuesta a validacion encuentas  \
0  Mediante el PRG_2023_281168 del 26 de enero se...   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                                   INVESTIGACIÓN E2E  \
0  1. se valida con el asesor Diego E Bustamante ...   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                                            Acciones Clasificacion  \
0  Es VIP comunicar mediante comunicado y hacer l...            NC   
1                                                NaN            NC   
2                                                NaN            NC   
3                                                NaN           POS   
4                                                NaN            NC   

  Recomendación Éxito Esfuerzo Emoción  
0     detractor     2        3       2  
1      promotor     5        5       5  
2      promotor     5        5       5  
3     detractor     1        1       1  
4     detractor     1        1       1  

[5 rows x 25 columns]

In [168]:
base_NC.shape

(66, 25)

In [170]:
verbatims_NC = base_NC["Verbatim"].to_numpy().tolist()
verbatims_NC[:10]

['Solicite una segunda modificaciòn y el asesor nunca me enviò la documentaciòn',
 'Primero agradecido por la atención de la asesora encargada del proceso, al banco el aceptar el cambio de tiempo de la hipoteca.',
 'Por la asesoría de mi asesora, pude lograr el cambio, ella es excelente yo la amo!!.. Feliz tarde!!',
 'Poca eficiencia ,no tienen representantes en mi ciudad, poca claridad y',
 'No se resolvió la error por parte del banco',
 'Me siento engañado por el banco porque en el momento de aprobación del crédito era en pesos y luego ni nos informaron cuando el desembolso y lo hicieron en uvr. El cual nos a traído muchos problemas. Luego hicimos el cambio de uvr a pesos y nos damos cuenta que el capital sigue subiendo.',
 'LOS INTERESES DEL CREDITO SON CRIMINALES, YA ESTOY BUSCANDO COMPRA DE CARTERA',
 'Lo peor tener esta clase de créditos',
 'La tasa pactada es mes vencido, un ajuste por unos dias en el mes del corte no debería alterar la tasa. Es matemática financiera ya que la t

In [195]:
verbatims_NC[36:66]

['Atendieron mi requerimiento con mucho compromiso',
 'Cumplieron con lo prometido inicialmente para el cambio del crédito',
 'Velocidad',
 'Son tasas no competitivas, siendo uno cliente del banco deberia uno tener un mejor trato.',
 'acceder a cualquier canal de leasing es casi imposible, el servicio del Banco es muy bueno y los canales apropiados, pero los de leasing son muy regulares. La sucursal virtual de leasing es cero amigable, la información no aparece completa, toca llamar a lalínea que es complicadísimo que atiendan. De verdad es muy complejo el servicio con leasing, siempre ha sido así y parece no mejorar con el tiempo. Gracias por leer mis comentarios.',
 'Mo me contactaron solo cambiaron la tasa',
 'cobertura y credibilidad',
 'No me parece bien que siendo una persona tan puntual con mis pagos no me quisieran hacer un mejoramiento de tasa',
 'falta de informacion por parte del banco cuando se realiza un abono que se debe sacar cita para cambiar las condiciones',
 'Me habí

In [196]:
classifier_robertuito(verbatims_NC[36:66])

[{'label': 'POS', 'score': 0.8047773241996765},
 {'label': 'NEU', 'score': 0.7662239074707031},
 {'label': 'NEU', 'score': 0.49578964710235596},
 {'label': 'NEG', 'score': 0.6002419590950012},
 {'label': 'NEG', 'score': 0.976251482963562},
 {'label': 'NEU', 'score': 0.6273913383483887},
 {'label': 'NEU', 'score': 0.7835972309112549},
 {'label': 'NEG', 'score': 0.9735121130943298},
 {'label': 'NEG', 'score': 0.9192532896995544},
 {'label': 'NEG', 'score': 0.789150595664978},
 {'label': 'POS', 'score': 0.9459633231163025},
 {'label': 'POS', 'score': 0.8532167077064514},
 {'label': 'NEG', 'score': 0.9542195796966553},
 {'label': 'NEG', 'score': 0.9518623948097229},
 {'label': 'NEG', 'score': 0.6285861730575562},
 {'label': 'NEU', 'score': 0.6291567087173462},
 {'label': 'NEU', 'score': 0.6150169372558594},
 {'label': 'NEU', 'score': 0.7294523119926453},
 {'label': 'POS', 'score': 0.711682915687561},
 {'label': 'NEG', 'score': 0.768030047416687},
 {'label': 'NEU', 'score': 0.75063031911849